package com.gov.iti.sakila.persistence.entities;// default package
// Generated Apr 7, 2023, 4:05:26 PM by Hibernate Tools 6.1.7.Final


import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

import org.hibernate.annotations.Proxy;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city"
        , catalog = "sakila"
)
public class City implements java.io.Serializable {


    private Short cityId;
    private Country country;
    private String city;
    private Date lastUpdate;
    private Set<Address> addresses = new HashSet<Address>(0);

    public City() {
    }

    public City(Short cityId, Country country, String city, Date lastUpdate) {
        this.cityId = cityId;
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
    }

    public City(Country country, String city, Date lastUpdate) {
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
    }

    public City(Country country, String city, Date lastUpdate, Set<Address> addresses) {
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
        this.addresses = addresses;
    }

    public City(Short cityId, Country country, String city, Date lastUpdate, Set<Address> addresses) {
        this.cityId = cityId;
        this.country = country;
        this.city = city;
        this.lastUpdate = lastUpdate;
        this.addresses = addresses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "city_id", unique = true, nullable = false)
    public Short getCityId() {
        return this.cityId;
    }

    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.PERSIST,CascadeType.REMOVE})
    @JoinColumn(name = "country_id", nullable = false)
    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }


    @Column(name = "city", nullable = false, length = 50)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update", nullable = false, length = 19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "city",cascade = CascadeType.REMOVE)
    public Set<Address> getAddresses() {
        return this.addresses;
    }

    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

    @Override
    public String toString() {
        return "City{" +
                "cityId=" + cityId +
                ", country=" + country.getCountry() +
                ", city='" + city + '\'' +
                ", lastUpdate=" + lastUpdate +
                ", addresses=" + addresses +
                '}';
    }
}


