POST  http://localhost:9090/Sakila/actor HTTP/1.1
Content-Type: text/xml


<soap:Envelope
 xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:jets="http://webService.sakila.iti.gov.com/">

   <soap:Body>
      <jets:getActorById>
         <id>2</id>
      </jets:getActorById>
   </soap:Body>
</soap:Envelope>